project_id = "jbzmcyycanrlnfhedcup"

[functions.sync-multas-detran]
verify_jwt = true

[functions.sync-veiculos-detran]
verify_jwt = true

[functions.ocr-documento]
verify_jwt = true

[functions.ocr-comprovante]
verify_jwt = true

[functions.bfleet-posicoes]
verify_jwt = true

[functions.frotas-roteirizar]
verify_jwt = true

[functions.programacao-rota-equipe]
verify_jwt = true

[functions.geocode-colaboradores]
verify_jwt = true

[functions.geocode-colaborador-base]
verify_jwt = true

[functions.botconversa-send]
verify_jwt = true

[functions.correios-prepostagem]
verify_jwt = true

[functions.correios-telegrama]
verify_jwt = true

[functions.correios-smt-auth]
verify_jwt = true

[functions.email-account-save]
verify_jwt = true
