/**
 * Configuração PM2 para execução contínua do sync de colaboradores
 *
 * Uso:
 *   pm2 start ecosystem.config.js
 *   pm2 save
 *   pm2 startup
 *   pm2 logs grm-sync-colaboradores
 */

// Carregar .env
require('dotenv').config();

module.exports = {
  apps: [
    {
      name: 'grm-sync-colaboradores',
      script: './grmserver-colaboradores-sync.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '*/5 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      log_file: './logs/combined.log',
      time_format: 'YYYY-MM-DD HH:mm:ss Z',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      max_restart_time: 3600000,
      min_uptime: 10000,
      kill_timeout: 5000,
      cwd: './',
    },
    {
      name: 'grm-sync-producao-diaria',
      script: './grm-sync-producao-diaria.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '1 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      kill_timeout: 5000,
      cwd: './',
    },
    {
      name: 'grm-sync-locais-embarque',
      script: './grm-sync-locais-embarque.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '2 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      kill_timeout: 5000,
      cwd: './',
    },
    {
      name: 'grm-sync-resultado-diario',
      script: './grm-sync-resultado-diario.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '3 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      kill_timeout: 5000,
      cwd: './',
    },
    {
      name: 'grm-sync-despesas',
      script: './grm-sync-despesas.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '4 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      kill_timeout: 5000,
      cwd: './',
    },
    {
      name: 'grm-sync-notas-fiscais',
      script: './grm-sync-notas-fiscais.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '5 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      kill_timeout: 5000,
      cwd: './',
    },
    {
      name: 'grm-sync-mapa-embarque',
      script: './grm-sync-mapa-embarque.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '6 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      kill_timeout: 5000,
      cwd: './',
    },
    {
      name: 'grm-sync-patrimonios',
      script: './grm-sync-patrimonios.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '7 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      kill_timeout: 5000,
      cwd: './',
    },
    {
      name: 'grm-sync-contas-pagar',
      script: './grm-sync-contas-pagar.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '8 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      kill_timeout: 5000,
      cwd: './',
    },
    {
      name: 'grm-sync-contas-receber',
      script: './grm-sync-contas-receber.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '9 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      kill_timeout: 5000,
      cwd: './',
    },
    {
      name: 'grm-sync-auditorias',
      script: './grm-sync-auditorias.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '10 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      kill_timeout: 5000,
      cwd: './',
    },
    {
      name: 'grm-sync-nhe',
      script: './grm-sync-nhe.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '11 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      kill_timeout: 5000,
      cwd: './',
    },
    {
      name: 'grm-sync-lista-os',
      script: './grm-sync-lista-os.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '12 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      kill_timeout: 5000,
      cwd: './',
    },
    {
      name: 'grm-sync-distribuicao-os',
      script: './grm-sync-distribuicao-os.js',
      instances: 1,
      exec_mode: 'fork',
      cron_restart: '13 * * * *',
      env: {
        NODE_ENV: 'production',
        GRMSERVER_USER: process.env.GRMSERVER_USER,
        GRMSERVER_PASSWORD: process.env.GRMSERVER_PASSWORD,
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_KEY: process.env.SUPABASE_KEY,
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.git'],
      max_restarts: 10,
      kill_timeout: 5000,
      cwd: './',
    },
  ],

  // Configuração de deploy (opcional)
  deploy: {
    production: {
      user: 'deploy',
      host: '144.126.131.137', // Ajustar para servidor real
      ref: 'origin/main',
      repo: 'git@github.com:seu-usuario/seu-repo.git', // Ajustar
      path: '/home/deploy/grm-sync',
      'post-deploy':
        'npm install && pm2 reload ecosystem.config.js --env production',
    },
  },
};
