from pathlib import Path

p = Path('agentes-grm-sync/grm-sync-lancar-nhe.js')
s = p.read_text(encoding='utf-8')

old = """      pendentes = pendentes.filter(function (item) {\n        return item.os === osSolicitada && (!args.data || item.data === ymd(args.data));\n      });\n      if (pendentes.length && args.funcionario) pendentes[0].funcionario = args.funcionario;\n      if (!pendentes.length) {\n        log('WARN', 'O.S. ' + osSolicitada + (args.data ? ' em ' + args.data : '') + ' não é elegível: pode existir carga/NHE no mesmo ponto, serviço fora do escopo ou ausência de informativo. --forcar não ignora esta regra.');\n      }\n"""

new = """      pendentes = pendentes.filter(function (item) {\n        return item.os === osSolicitada && (!args.data || item.data === ymd(args.data));\n      });\n\n      // Um --dry-run valida o formulário mas grava DRY_RUN_OK, que de propósito\n      // não entra na fila histórica automática. Quando o operador pede\n      // explicitamente a MESMA O.S.+data depois do teste, reconstrói somente\n      // esse candidato a partir da auditoria. As travas reais abaixo continuam\n      // obrigatórias: NHE/movimento existente, situação da O.S., serviço, login\n      // e geofence são recalculados antes de qualquer Salvar.\n      if (!pendentes.length && args.data) {\n        var dataSolicitada = ymd(args.data);\n        var dryResult = await supabase\n          .from(TABLE_RESULTADOS)\n          .select('data_referencia,numero_os,cliente,supervisao,funcionario,status,raw')\n          .eq('data_referencia', dataSolicitada)\n          .eq('numero_os', osSolicitada)\n          .eq('status', 'DRY_RUN_OK')\n          .limit(1)\n          .maybeSingle();\n        if (dryResult.error) throw dryResult.error;\n        if (dryResult.data) {\n          var dryRow = dryResult.data;\n          pendentes = [{\n            data: dryRow.data_referencia,\n            data_br: brDate(dryRow.data_referencia),\n            os: normOs(dryRow.numero_os),\n            cliente: dryRow.cliente,\n            supervisao: dryRow.supervisao,\n            funcionario: dryRow.raw && dryRow.raw.colaborador_original ? dryRow.raw.colaborador_original : dryRow.funcionario,\n            osCoord: undefined,\n            reprocessamento: true,\n            statusAnterior: 'DRY_RUN_OK'\n          }];\n          log('INFO', 'O.S. ' + osSolicitada + ' em ' + dataSolicitada + ': reaberta manualmente após DRY_RUN_OK; travas de segurança serão revalidadas.');\n        }\n      }\n\n      if (pendentes.length && args.funcionario) pendentes[0].funcionario = args.funcionario;\n      if (!pendentes.length) {\n        log('WARN', 'O.S. ' + osSolicitada + (args.data ? ' em ' + args.data : '') + ' não é elegível: pode existir carga/NHE no mesmo ponto, serviço fora do escopo ou ausência de informativo. --forcar não ignora esta regra.');\n      }\n"""

if s.count(old) != 1:
    raise SystemExit('anchor modo manual nao encontrado exatamente uma vez')

s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')
