-- Lote 2 da conciliação de hotéis da planilha "bc hoteis.xlsx".
begin;

select public.hospedagem_conciliar_hotel(
  v.nome,
  v.cidade,
  v.uf,
  v.link_maps,
  v.whatsapp,
  v.endereco,
  v.valor_padrao,
  v.valor_individual,
  v.valor_duplo,
  v.valor_triplo,
  v.valor_quadruplo,
  v.prioridade,
  v.observacoes
)
from (
values
  (E'HOTEL IMPERIAL', E'BAIXA GRANDE DO RIBEIRO', E'PI', E'https://maps.app.goo.gl/hcRJkdZ93WeR7dBd8', E'+5589981033371', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL DUAGRO', E'BAIXA GRANDE DO RIBEIRO', E'PI', NULL, E'+5589981285865', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL MARAVILHA', E'BALSAS', E'MA', E'https://maps.app.goo.gl/wyDA4nzWN1YaJgef8', NULL, NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'POUSADA DA CLEUSA', E'BAMBUI', E'MG', NULL, E'+5537999614207', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL RAFFA', E'BANDEIRANTES', E'MS', E'https://maps.app.goo.gl/2feU66vFuvHqa2sS6', E'+556799828337', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'BIS HOTEL', E'BANDEIRANTES', E'MS', E'https://maps.app.goo.gl/DHcRAzDoYiaL8rkP8', E'+556796990988', NULL, 150.00, 150.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'CASINHA HOSPEDAGEM', E'BARIRI', E'SP', E'https://maps.app.goo.gl/Yh9Cm2Pov31MjACg7', NULL, NULL, 135.00, 135.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL CARVALHOS', E'BARRA DO OURO', E'TO', E'https://maps.app.goo.gl/kN4DuG1FuM5uzRJU9', E'+5563992419389', NULL, 100.00, 100.00, 90.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL APICE', E'BARREIRAS', E'BA', E'https://maps.app.goo.gl/vBii5WCY2k5J4tkB9', E'+5577999327696', NULL, 130.00, 130.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'APICE HOTEL', E'BARREIRAS', E'BA', E'https://maps.app.goo.gl/JLZoYdN2idX5vBgD9', E'+5577999327696', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL PALACE', E'BARRETOS', E'SP', E'https://maps.app.goo.gl/XRBDpSbzipnz2tK98', E'+551733222825', NULL, 111.00, 111.00, 101.50, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL TERRA NOVA', E'BATAGUASSU', E'MS', E'https://maps.app.goo.gl/dxVYf3nSaKeBvYKG6', NULL, NULL, 200.00, 200.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL EUROPA', E'BATAGUASSU', E'MS', E'https://maps.app.goo.gl/g8CUvVxidrgzBDWj7', NULL, NULL, 150.00, 150.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL SANTARÉM IV', E'BATAYPORA', E'MS', NULL, E'+5567999787475', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL BRASIL', E'BEBEDOURO', E'SP', E'https://maps.app.goo.gl/NrF1sMate4NkVx459', E'+5517981294121', NULL, 85.00, 85.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'VICTORIA PALACE HOTEL', E'BELA VISTA DE GOIÁS', E'GO', E'https://maps.app.goo.gl/1gVkwBT8gUpRdf2P6', E'+556235511173', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL ROTA 020', E'BELA VISTA DE GOIÁS', E'GO', E'https://maps.app.goo.gl/Y3uYKrHip79b3R7t9', E'+556296798534', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'VIA VIAGEM HOTEL', E'BIRIGUI', E'SP', E'https://maps.app.goo.gl/x8PdKiojpzv3AieB8', NULL, NULL, 102.00, 102.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'POUSADA TROPICALIA', E'BIRIGUI', E'SP', E'https://maps.app.goo.gl/MpQG7AAcgZvbw9qT8', NULL, NULL, 70.00, 70.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL FLOR DO SERRADO', E'BOA ESPERANÇA DO NORTE', E'MT', E'https://maps.app.goo.gl/TNGcz6tsBgvgBmjMA', NULL, NULL, 195.00, NULL, 195.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'POUSADA JAQUELINE', E'BOM DESPACHO', E'MG', E'https://maps.app.goo.gl/vQaBiBAsykRyHJq88', E'+553735227115', NULL, 100.00, 100.00, 100.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'ALFA HOTEL', E'BOM DESPACHO', E'MG', E'https://maps.app.goo.gl/LnSG4YvtixXN6z9g7', NULL, NULL, 107.00, 107.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL DIPLOMATA', E'BOM JESUS DE GOIAS', E'GO', E'https://maps.app.goo.gl/5NMLubWJS6NMrbmj6', E'+556499487014', NULL, 70.00, NULL, 70.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL ANGELINA', E'BOM JESUS', E'RS', E'https://maps.app.goo.gl/i4yT1RMG24cZvScFA', NULL, NULL, 94.00, 94.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'OSCAR HOTEL', E'BONFINOPOLIS', E'MG', E'https://maps.app.goo.gl/PXh3xvUt55bLhGxw7', NULL, NULL, 143.00, 143.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL IBIZA', E'BONOPOLIS', E'GO', E'https://maps.app.goo.gl/GnWMbDgMBXcbpgv79', NULL, NULL, 141.00, NULL, 141.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL CENTRAL', E'BRASILÂNDIA DE MINAS', E'MG', E'https://maps.app.goo.gl/vWBrcZThyw6YccnP6', NULL, NULL, 124.00, 124.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL E CHURRASCARIA IVAÍ', E'BRASNORTE', E'MT', E'https://maps.app.goo.gl/qUYKQdHrcQ9TMzjBA', NULL, NULL, 100.00, NULL, NULL, 100.00, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'POUSADA PORTAL DO SOL', E'BRITÂNIA', E'GO', E'https://maps.app.goo.gl/o5wwqR2344fjRfQk8', E'+556292613103', NULL, 100.00, 100.00, 75.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'POUSADA DO SIMÃO', E'BRITÂNIA', E'GO', E'https://maps.app.goo.gl/bPdw35sAotdLVYRj8', E'+556282189720', NULL, 285.00, 285.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'CLAUDIO''S HOTEL', E'BRITÂNIA', E'GO', E'https://maps.app.goo.gl/MYqr7LqtpUR59B1FA', E'+556283195594', NULL, 258.00, NULL, 258.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'WF HOTEL', E'BURITIS', E'MG', E'https://maps.app.goo.gl/mgNhnNSWQkR8PDzW9', NULL, NULL, 90.00, NULL, NULL, 90.00, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL STAR PLAZZA', E'CABEICEIRAS', E'GO', E'https://maps.app.goo.gl/XXVFFVEAR3AZhCy9A', E'+556199536368', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL CAETANO', E'CAIAPONIA', E'GO', E'https://maps.app.goo.gl/wt2jdTVMFXdxhswW7', E'+5564996233406', NULL, 120.00, 120.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL E CHURRASCARIA MINEIRA', E'CAMPINA VERDE', E'MG', E'https://maps.app.goo.gl/bkyBrLG1e4swDzNJA', NULL, NULL, 601.00, 601.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL PEREIRA', E'CAMPINORTE', E'GO', E'https://maps.app.goo.gl/S7ACayjc1bCKFcZx9', E'+556233473603', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL CONFORT', E'CAMPO ALEGRE DE GOIAS', E'GO', E'https://maps.app.goo.gl/YgfdQnCnL1tc2YnW8', NULL, NULL, 96.00, 96.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL AVENIDA', E'CAMPO ERÊ', E'SC', E'https://maps.app.goo.gl/A4pMSxo2Nyx6NtbS6', E'+554999144575', NULL, 100.00, 100.00, 100.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL AVENIDA JK', E'CAMPOS NOVOS', E'SC', E'https://maps.app.goo.gl/RJwAY1gsLt2GiaWA6', E'+554984224450', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'GOLDONI HOTEL AVENIDA', E'CAPANEMA', E'PR', E'https://maps.app.goo.gl/b9hcqMD9DJTfMtcdA', E'+5546999418080', NULL, 140.00, 140.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'ALFONSO''S HOTEL', E'CASA BRANCA', E'SP', E'https://maps.app.goo.gl/917KJq8QTpGEDVE58', E'+551936714392', NULL, 180.00, 180.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL SAUIPE', E'CASCAVEL', E'PR', E'https://maps.app.goo.gl/uuDUWnJP26zcXa4K7', E'+554591453962', NULL, 230.00, 230.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL MELLO', E'CASCAVEL', E'PR', E'https://maps.app.goo.gl/yma8BU2JVjS7dSc66', NULL, NULL, 155.00, 155.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'RAPHA''S HOTEL', E'CATALÃO', E'GO', E'https://maps.app.goo.gl/c3SXvadP7GF9993B8', E'+556481178366', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'DORMITÓRIO ELIETE', E'CHAPADA GAUCHA', E'MG', E'https://maps.app.goo.gl/je2UKcDqLkGfuUSr7', E'+5538998571096', NULL, 290.00, 290.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL E DORMITÓRIO NUNES', E'CHAPADÃO DO CÉU', E'GO', E'https://maps.app.goo.gl/T2Lx1mGqJugMujeG9', E'+5564996955578', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx')
) as v(
  nome,
  cidade,
  uf,
  link_maps,
  whatsapp,
  endereco,
  valor_padrao,
  valor_individual,
  valor_duplo,
  valor_triplo,
  valor_quadruplo,
  prioridade,
  observacoes
);

commit;
