-- Histórico da leitura OCR e da comparação das cargas na tela
-- Logística > O.S. > Conferências.
create table if not exists public.logistica_pre_conferencia_os (
  id bigint generated by default as identity primary key,
  os_id text not null unique,
  numero_os text not null,
  laudo_urls jsonb not null default '[]'::jsonb,
  cargas_sistema jsonb not null default '[]'::jsonb,
  cargas_ocr jsonb not null default '[]'::jsonb,
  resultado jsonb not null default '[]'::jsonb,
  status text not null default 'PRE_CONFERIDA'
    check (status in ('PRE_CONFERIDA', 'CONFIRMADA')),
  criado_por uuid null,
  atualizado_por uuid null,
  confirmado_por uuid null,
  confirmado_em timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists logistica_pre_conferencia_os_numero_idx
  on public.logistica_pre_conferencia_os (numero_os);

create index if not exists logistica_pre_conferencia_os_status_idx
  on public.logistica_pre_conferencia_os (status, updated_at desc);

alter table public.logistica_pre_conferencia_os enable row level security;

drop policy if exists "logistica_pre_conferencia_select" on public.logistica_pre_conferencia_os;
create policy "logistica_pre_conferencia_select"
  on public.logistica_pre_conferencia_os
  for select
  to authenticated
  using (true);

drop policy if exists "logistica_pre_conferencia_insert" on public.logistica_pre_conferencia_os;
create policy "logistica_pre_conferencia_insert"
  on public.logistica_pre_conferencia_os
  for insert
  to authenticated
  with check (auth.uid() = criado_por or criado_por is null);

drop policy if exists "logistica_pre_conferencia_update" on public.logistica_pre_conferencia_os;
create policy "logistica_pre_conferencia_update"
  on public.logistica_pre_conferencia_os
  for update
  to authenticated
  using (true)
  with check (auth.uid() = atualizado_por or atualizado_por is null);

grant select, insert, update on public.logistica_pre_conferencia_os to authenticated;
grant usage, select on sequence public.logistica_pre_conferencia_os_id_seq to authenticated;
