-- Fila do OCR local (PaddleOCR) usado em Logística > O.S. > Conferências.
-- O navegador cria o job por Edge Function, o worker no VPS processa e grava o resultado.

create table if not exists public.logistica_ocr_jobs (
  id bigint generated by default as identity primary key,
  request_user_id uuid not null,
  os_id text null,
  numero_os text null,
  document_url text not null,
  file_type text not null check (file_type in ('jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf')),
  instruction text null,
  status text not null default 'PENDENTE'
    check (status in ('PENDENTE', 'PROCESSANDO', 'CONCLUIDO', 'ERRO', 'CANCELADO')),
  priority integer not null default 100,
  progress smallint not null default 0 check (progress between 0 and 100),
  page_current integer null,
  page_total integer null,
  attempts integer not null default 0,
  worker_id text null,
  locked_at timestamptz null,
  started_at timestamptz null,
  completed_at timestamptz null,
  result jsonb null,
  raw_text text null,
  raw_ocr jsonb null,
  error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days')
);
create index if not exists logistica_ocr_jobs_queue_idx
  on public.logistica_ocr_jobs (status, priority desc, created_at asc);
create index if not exists logistica_ocr_jobs_user_idx
  on public.logistica_ocr_jobs (request_user_id, created_at desc);
create index if not exists logistica_ocr_jobs_os_idx
  on public.logistica_ocr_jobs (numero_os, created_at desc);
create index if not exists logistica_ocr_jobs_expiry_idx
  on public.logistica_ocr_jobs (expires_at);
alter table public.logistica_ocr_jobs enable row level security;
drop policy if exists "logistica_ocr_jobs_select_own" on public.logistica_ocr_jobs;
create policy "logistica_ocr_jobs_select_own"
  on public.logistica_ocr_jobs
  for select
  to authenticated
  using (auth.uid() = request_user_id);
grant select on public.logistica_ocr_jobs to authenticated;
grant usage, select on sequence public.logistica_ocr_jobs_id_seq to authenticated;
create table if not exists public.logistica_ocr_workers (
  worker_id text primary key,
  hostname text null,
  version text null,
  status text not null default 'ONLINE'
    check (status in ('ONLINE', 'PROCESSANDO', 'ERRO', 'PARADO')),
  current_job_id bigint null,
  details jsonb not null default '{}'::jsonb,
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists logistica_ocr_workers_last_seen_idx
  on public.logistica_ocr_workers (last_seen desc);
alter table public.logistica_ocr_workers enable row level security;
drop policy if exists "logistica_ocr_workers_select" on public.logistica_ocr_workers;
create policy "logistica_ocr_workers_select"
  on public.logistica_ocr_workers
  for select
  to authenticated
  using (true);
grant select on public.logistica_ocr_workers to authenticated;
-- Retira atomicamente um job da fila. SKIP LOCKED permite mais de um worker no futuro.
create or replace function public.claim_logistica_ocr_job(p_worker_id text)
returns setof public.logistica_ocr_jobs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_job_id bigint;
begin
  select j.id
    into v_job_id
  from public.logistica_ocr_jobs j
  where j.attempts < 3
    and (
      j.status = 'PENDENTE'
      or (j.status = 'PROCESSANDO' and j.locked_at < now() - interval '20 minutes')
    )
  order by j.priority desc, j.created_at asc
  for update skip locked
  limit 1;

  if v_job_id is null then
    return;
  end if;

  update public.logistica_ocr_jobs
     set status = 'PROCESSANDO',
         worker_id = p_worker_id,
         attempts = attempts + 1,
         progress = greatest(progress, 1),
         locked_at = now(),
         started_at = coalesce(started_at, now()),
         error = null,
         updated_at = now()
   where id = v_job_id;

  return query
    select * from public.logistica_ocr_jobs where id = v_job_id;
end;
$$;
revoke all on function public.claim_logistica_ocr_job(text) from public, anon, authenticated;
grant execute on function public.claim_logistica_ocr_job(text) to service_role;
comment on table public.logistica_ocr_jobs is
  'Fila assíncrona de documentos processados pelo PaddleOCR no VPS da Grão 1000.';
comment on function public.claim_logistica_ocr_job(text) is
  'Reserva atomicamente o próximo job de OCR para um worker local.';
