-- Lote 1 da conciliação de hotéis da planilha "bc hoteis.xlsx".
begin;

select public.hospedagem_conciliar_hotel(
  v.nome,
  v.cidade,
  v.uf,
  v.link_maps,
  v.whatsapp,
  v.endereco,
  v.valor_padrao,
  v.valor_individual,
  v.valor_duplo,
  v.valor_triplo,
  v.valor_quadruplo,
  v.prioridade,
  v.observacoes
)
from (
values
  (E'POUSADA VALE DO ARAGUAIA', E'ABREULANDIA', E'MG', E'https://maps.app.goo.gl/oh7HbfPxR8j7L7Gm6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL VITÓRIA', E'ACREUNA', E'GO', E'https://maps.app.goo.gl/ZPnUaWr6egsj3Jub7', E'+5564992426116', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'POLYANNA HOTEL', E'AGUA BOA', E'MT', E'https://maps.app.goo.gl/meBoYC4zaXGZJxz48', E'+5566999943961', NULL, 120.00, 120.00, 110.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'PLANALTO HOTEL', E'AGUA BOA', E'MT', E'https://maps.app.goo.gl/2hBd5oSJxdW28m2LA', E'+5566981344001', NULL, 100.00, 100.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL LÍDER', E'AGUA BOA', E'MT', E'https://maps.app.goo.gl/Q6u3kNEMKHUR8wVeA', E'+5566992295148', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL ÁGUA DOCE', E'ÁGUA DOCE', E'SC', E'https://maps.app.goo.gl/ruBDXGAaBPJ6EYsf7', E'+554999273864', NULL, 80.00, 80.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL TROPICAL', E'ALEXANIA', E'GO', E'https://maps.app.goo.gl/zHBYb8NG1fJUfDVM7', E'+556282447089', NULL, 80.00, 80.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL MIRANDA', E'ALEXANIA', E'GO', E'https://maps.app.goo.gl/od3VZv5WdzW2G6MY8', E'+556292298015', NULL, 114.00, 114.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL BEM ME QUER', E'ALEXANIA', E'GO', E'https://maps.app.goo.gl/gSauormhsZjQWNQ66', E'+5562992616331', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'MM ALIANÇA HOTEL', E'ALIANCA DO TOCANTINS', E'TO', E'https://maps.app.goo.gl/i7MU9Yk27b5DcoEk7', NULL, NULL, 140.00, 140.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL DO GAUCHO', E'ALMAS', E'TO', E'https://maps.app.goo.gl/Jwq5AQofMdkq3A4E9', NULL, NULL, 80.00, NULL, 80.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL CARDOSO', E'ALMAS', E'TO', E'https://maps.app.goo.gl/nv5oTUHhXJeXJTSZ6', NULL, NULL, 75.00, NULL, 75.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL JACARANDÁ', E'ALMERINDONOPOLIS', E'GO', E'https://maps.app.goo.gl/X5PBAj4LWKdzVW6T3', E'+5564996656167', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'MINAS HOTEL', E'ALTA FLORESTA', E'MT', E'https://maps.app.goo.gl/U9HTaMrWA7Z9Ua5V9', E'+5566984332670', NULL, 90.00, 90.00, 90.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL VENEZA', E'ALTA FLORESTA', E'MT', E'https://maps.app.goo.gl/7VEHW2CxpbvFgoiS7', E'+5566997130108', NULL, 120.00, 120.00, NULL, NULL, NULL, E'EVITAR', E'Fonte: bc hoteis.xlsx | Contato marcado como evitar: NUNCA MAIS ESTE HOTEL - Hotel Veneza - Alta Florestal/MT'),
  (E'HOTEL LUZ DIVINA', E'ALTA FLORESTA', E'MT', E'https://maps.app.goo.gl/HoheBdyDsG3EVkk29', NULL, NULL, 135.00, NULL, 135.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL SILVEIRA', E'ALTEROSA', E'MG', E'https://maps.app.goo.gl/YmrTdtuydbmx67VF9', NULL, NULL, 65.00, 65.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL CENTRAL', E'ALTEROSA', E'MG', E'https://maps.app.goo.gl/oCdTNF86KSAZVpAY8', NULL, NULL, 130.00, 130.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'FAZENDA PEQUENA HOLANDA', E'ALTO PARNAÍBA', E'MA', E'https://maps.app.goo.gl/XjreBsF4dKSWs6Lo8', NULL, NULL, 50.00, 50.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL PALACE RECANTO DO SOL 2', E'ALTO TAQUARI', E'MT', E'https://maps.app.goo.gl/QbasgJffmxy4Kq7V9', NULL, NULL, 85.00, NULL, 85.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL KARAJAS', E'ALTO TAQUARI', E'MT', E'https://maps.app.goo.gl/CAFDab8B1gDfGbcg9', NULL, NULL, 80.00, 80.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL VITORIA', E'ALVORADA', E'TO', E'https://maps.app.goo.gl/kiCTtgycZ2ggNPE76', NULL, NULL, 73.30, NULL, NULL, 73.30, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL GUAPORE', E'ALVORADA', E'TO', NULL, E'+5563992401515', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL ALVORADA', E'ALVORADA', E'TO', E'https://maps.app.goo.gl/XQbpjBviswEUuHhN8', E'+5563992401515', NULL, 160.00, 160.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'KAREN HOTEL', E'AMAMBAI', E'MS', E'https://maps.app.goo.gl/5pCadS1NzEMUbApY8', NULL, NULL, 75.00, NULL, NULL, 75.00, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL GLOBAL PALACE', E'AMAMBAI', E'MS', E'https://maps.app.goo.gl/pat7pmzjdfFt9wsP7', NULL, NULL, 91.66, NULL, 91.66, 91.68, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL AMAMBAI', E'AMAMBAI', E'MS', E'https://maps.app.goo.gl/XPj6E84NenbMcLXQ6', E'+556734812577', NULL, 89.90, 89.90, NULL, 99.97, 100.00, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL JR', E'ANANAS', E'TO', NULL, E'+5563991383086', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'INGA PALACE HOTEL', E'ANDIRÁ', E'PR', E'https://maps.app.goo.gl/ZZXr3uhNHuxwSyt6', E'+554335383939', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL PORTAL DO JALAPÃO', E'APARECIDA DO RIO NEGRO', E'TO', E'https://maps.app.goo.gl/tcbCLU8pmFBpVJDw7', E'+556399438467', NULL, 100.00, 100.00, 100.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL PRAIA & MAR LTDA', E'ARACAJU', E'SE', E'https://maps.app.goo.gl/GTD6FxpoduFxgZy2A', E'+557932434520', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL DA GAÚCHA', E'ARAGARÇAS', E'MT', E'https://maps.app.goo.gl/aqcQ5if35iR5HfP4A', E'+556692237999', NULL, 130.00, 130.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL SERRANOS', E'ARAGUACEMA', E'TO', E'https://maps.app.goo.gl/E4XPcitMCa3eDfs27', E'+5563985119435', NULL, 120.00, 120.00, 75.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL APARECIDENSE', E'ARAGUAÍNA', E'TO', NULL, E'+5563992361419', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL ACONCHEGO', E'ARAGUAPAZ', E'GO', E'https://maps.app.goo.gl/knVmL17bjgnv4dNW7', E'+5562992933463', NULL, 100.00, 100.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL TERRAÇO', E'ARAGUARI', E'MG', E'https://maps.app.goo.gl/BxmFwtwtz5mfbUfS8', E'+5534988610847', NULL, 120.00, 120.00, 110.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL ORSI', E'ARAGUARI', E'MG', NULL, E'+553435126790', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL CAMPOS FLORIDOS', E'ARAPOTI', E'PR', E'https://maps.app.goo.gl/T4vbPyAUjKnq7Thy8', E'+5543999807231', NULL, 136.00, 136.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL COLUCCIO', E'ARARAQUARA', E'SP', E'https://maps.app.goo.gl/rDqWfUVCYgYUrJpJ6', E'+5516997824054', NULL, 87.50, NULL, 87.50, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'POUSADA ACONCHEGO', E'ARAXA', E'MG', E'https://maps.app.goo.gl/TPdisErXVE5W1gA26', E'+5534988510770', NULL, NULL, NULL, NULL, NULL, NULL, E'EVITAR', E'Fonte: bc hoteis.xlsx | Contato marcado como evitar: NÃO RESERVAR AQUI - Pousada Aconchego Araxá MG'),
  (E'BIG HOTEL', E'ARINOS', E'MG', E'https://maps.app.goo.gl/mqQJ8uy62dVAJe9Z7', E'+5538999505867', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL NICLOTTE', E'ARIPUANA', E'MT', E'https://maps.app.goo.gl/s7jYjaEWCPvxwCdj9', E'+5566981293695', NULL, 120.00, 120.00, 85.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'AMAZONIA HOTEL', E'ARIPUANA', E'MT', E'https://maps.app.goo.gl/MNrkspNtPkoLnoef9', NULL, NULL, 88.34, 88.34, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL POUSADA AQUARIUS', E'ARUANÃ', E'GO', E'https://maps.app.goo.gl/xKwDaaV2vhy9wrvr5', E'+556291755353', NULL, 120.00, 120.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL IBAJE', E'BAGE', E'RS', E'https://maps.app.goo.gl/FreTTvG4k6ka5Ahm9', E'+5553991582170', NULL, 95.00, NULL, 95.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'APART HOTEL VITRINE', E'BAGE', E'RS', E'https://maps.app.goo.gl/RdpidYZCv38s4Tog6', NULL, NULL, 110.00, 110.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx')
) as v(
  nome,
  cidade,
  uf,
  link_maps,
  whatsapp,
  endereco,
  valor_padrao,
  valor_individual,
  valor_duplo,
  valor_triplo,
  valor_quadruplo,
  prioridade,
  observacoes
);

commit;
