-- Agente de liberação de despesas: Programação do Gestor -> GRM.
-- A fila é por CPF, versionada e idempotente. O worker existente continua
-- serializando todos os agentes GRM; esta estrutura adiciona uma segunda trava
-- lógica por colaborador para impedir que uma versão antiga sobrescreva a nova.

create extension if not exists pgcrypto;

create table if not exists public.grm_despesas_tipos_config (
  chave text primary key,
  origem text not null check (origem in ('ALIMENTACAO', 'DESLOCAMENTO', 'EXTRA')),
  tipo_grm text not null,
  valor_padrao numeric(12,2),
  exibir boolean not null default true,
  auto boolean not null default false,
  carga_nhe boolean not null default true,
  max_mov_dia integer not null default 1 check (max_mov_dia >= 0),
  ativo boolean not null default false,
  observacao text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.grm_despesas_tipos_config is
  'Mapeamento configurável entre despesas da Programação e o nome exato existente em Regras de Caixa Operacional no GRM.';

-- Somente o tipo confirmado visualmente nas telas fornecidas começa ativo.
-- Os demais ficam cadastrados, porém inativos, até o nome/valor exato ser
-- conferido no GRM. Isso impede liberação com categoria ou limite inventado.
insert into public.grm_despesas_tipos_config
  (chave, origem, tipo_grm, valor_padrao, exibir, auto, carga_nhe, max_mov_dia, ativo, observacao)
values
  ('ALIMENTACAO_CAFE', 'ALIMENTACAO', 'Café', null, true, false, true, 1, false,
   'Definir o valor e confirmar o nome exato no GRM antes de ativar.'),
  ('ALIMENTACAO_ALMOCO', 'ALIMENTACAO', 'Almoço', 30.00, true, false, true, 1, true,
   'Valor inicial reproduz a configuração apresentada na tela do GRM; pode ser alterado nesta tabela.'),
  ('ALIMENTACAO_JANTA', 'ALIMENTACAO', 'Janta', null, true, false, true, 1, false,
   'Definir o valor e confirmar o nome exato no GRM antes de ativar.'),
  ('DESLOCAMENTO_UBER_TAXI', 'DESLOCAMENTO', 'Ajuda de Custo', null, true, false, true, 1, false,
   'Nome/valor precisam ser validados no GRM.'),
  ('DESLOCAMENTO_REEMBOLSO_KM', 'DESLOCAMENTO', 'AJUSTE DE SALDO', null, true, false, true, 1, false,
   'Nome/valor precisam ser validados no GRM.'),
  ('EXTRA_RECARGA', 'EXTRA', 'Recarga', null, true, false, true, 1, false,
   'Confirmar categoria e valor no GRM.'),
  ('EXTRA_LAVANDERIA', 'EXTRA', 'Lavanderia', null, true, false, true, 1, false,
   'Confirmar categoria e valor no GRM.'),
  ('EXTRA_LAVAGEM_VEICULO', 'EXTRA', 'Lavagem de Veículo', null, true, false, true, 1, false,
   'Confirmar categoria e valor no GRM.'),
  ('EXTRA_OUTROS', 'EXTRA', 'Outros', null, true, false, true, 1, false,
   'Confirmar categoria e valor no GRM.')
on conflict (chave) do nothing;

create table if not exists public.grm_despesas_versoes (
  id uuid primary key default gen_random_uuid(),
  sequencia bigint generated by default as identity,
  gestor_id uuid,
  regional text not null,
  data_referencia date not null,
  motivo text not null check (motivo in (
    'INATIVIDADE_5_MIN',
    'TROCA_DE_TELA',
    'FECHAMENTO_JANELA',
    'SALVAR_MANUAL',
    'RECONCILIACAO'
  )),
  programacao_ids jsonb not null default '[]'::jsonb,
  resumo jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists grm_despesas_versoes_regional_data_idx
  on public.grm_despesas_versoes (regional, data_referencia, created_at desc);

create table if not exists public.grm_despesas_estado_colaborador (
  cpf text primary key check (cpf ~ '^\d{11}$'),
  colaborador_id text,
  nome text not null,
  regional_origem text,
  versao_desejada_id uuid references public.grm_despesas_versoes(id) on delete set null,
  hash_desejado text,
  regras_desejadas jsonb not null default '[]'::jsonb,
  deve_liberar boolean not null default false,
  hash_aplicado text,
  status_aplicacao text not null default 'PENDENTE' check (status_aplicacao in (
    'PENDENTE', 'PROCESSANDO', 'APLICADO', 'LIMPO', 'DIVERGENTE', 'ERRO'
  )),
  aplicado_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists grm_despesas_estado_versao_idx
  on public.grm_despesas_estado_colaborador (versao_desejada_id);

create table if not exists public.grm_despesas_fila (
  id uuid primary key default gen_random_uuid(),
  versao_id uuid not null references public.grm_despesas_versoes(id) on delete cascade,
  programacao_id text,
  data_referencia date not null,
  regional text not null,
  colaborador_id text,
  nome text not null,
  cpf text not null check (cpf ~ '^\d{11}$'),
  acao text not null check (acao in ('APLICAR', 'LIMPAR')),
  regras jsonb not null default '[]'::jsonb,
  hash_desejado text not null,
  status text not null default 'PENDENTE' check (status in (
    'PENDENTE',
    'PROCESSANDO',
    'APLICADO',
    'LIMPO',
    'IGNORADO_VERSAO_SUPERADA',
    'DIVERGENTE',
    'ERRO'
  )),
  tentativas integer not null default 0,
  max_tentativas integer not null default 3 check (max_tentativas > 0),
  ultimo_erro text,
  diagnostico jsonb not null default '{}'::jsonb,
  screenshot_path text,
  locked_at timestamptz,
  finalizado_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists grm_despesas_fila_status_idx
  on public.grm_despesas_fila (status, created_at);
create index if not exists grm_despesas_fila_cpf_idx
  on public.grm_despesas_fila (cpf, created_at desc);
create index if not exists grm_despesas_fila_versao_idx
  on public.grm_despesas_fila (versao_id);

create unique index if not exists grm_despesas_fila_pendente_hash_uidx
  on public.grm_despesas_fila (cpf, hash_desejado)
  where status in ('PENDENTE', 'PROCESSANDO');

create or replace function public.grm_despesas_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists grm_despesas_tipos_config_touch on public.grm_despesas_tipos_config;
create trigger grm_despesas_tipos_config_touch
before update on public.grm_despesas_tipos_config
for each row execute function public.grm_despesas_touch_updated_at();

drop trigger if exists grm_despesas_estado_touch on public.grm_despesas_estado_colaborador;
create trigger grm_despesas_estado_touch
before update on public.grm_despesas_estado_colaborador
for each row execute function public.grm_despesas_touch_updated_at();

drop trigger if exists grm_despesas_fila_touch on public.grm_despesas_fila;
create trigger grm_despesas_fila_touch
before update on public.grm_despesas_fila
for each row execute function public.grm_despesas_touch_updated_at();

-- Reclama uma única alteração de forma atômica. ERRO com tentativas restantes
-- volta à fila; PROCESSANDO travado há 20 minutos também pode ser recuperado.
create or replace function public.claim_next_grm_despesa_fila()
returns public.grm_despesas_fila
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.grm_despesas_fila;
begin
  perform pg_advisory_xact_lock(hashtext('claim_next_grm_despesa_fila'));

  update public.grm_despesas_fila
     set status = 'ERRO',
         ultimo_erro = coalesce(ultimo_erro, 'Processamento anterior excedeu 20 minutos.'),
         locked_at = null
   where status = 'PROCESSANDO'
     and locked_at < now() - interval '20 minutes';

  select *
    into v_row
    from public.grm_despesas_fila
   where (
      status = 'PENDENTE'
      or (status = 'ERRO' and tentativas < max_tentativas)
   )
   order by created_at asc
   for update skip locked
   limit 1;

  if v_row.id is null then
    return null;
  end if;

  update public.grm_despesas_fila
     set status = 'PROCESSANDO',
         tentativas = tentativas + 1,
         locked_at = now(),
         ultimo_erro = null
   where id = v_row.id
   returning * into v_row;

  update public.grm_despesas_estado_colaborador
     set status_aplicacao = 'PROCESSANDO'
   where cpf = v_row.cpf
     and hash_desejado = v_row.hash_desejado;

  return v_row;
end;
$$;

revoke all on function public.claim_next_grm_despesa_fila() from public;
grant execute on function public.claim_next_grm_despesa_fila() to service_role;

alter table public.grm_despesas_tipos_config enable row level security;
alter table public.grm_despesas_versoes enable row level security;
alter table public.grm_despesas_estado_colaborador enable row level security;
alter table public.grm_despesas_fila enable row level security;

-- Nenhuma policy para anon/authenticated: a escrita e a leitura operacional
-- são feitas exclusivamente pela Edge Function e pelo worker com service role.
-- Isso evita expor CPF, limites e diagnósticos de outros colaboradores no
-- navegador. Consultas administrativas continuam disponíveis no SQL Editor.
