create table if not exists public.metas_auditoria (
  id bigint generated by default as identity primary key,
  ano integer not null check (ano between 2000 and 2100),
  mes integer not null check (mes between 1 and 12),
  regional text not null,
  valor_auditoria numeric not null default 0,
  total_embarcado numeric not null default 0,
  percentual_limite numeric not null check (percentual_limite between 0 and 100),
  apto boolean not null default true,
  nome_arquivo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (ano, mes, regional)
);

alter table public.metas_auditoria enable row level security;

create policy "metas_auditoria_select_authenticated" on public.metas_auditoria for select to authenticated using (true);
create policy "metas_auditoria_insert_authenticated" on public.metas_auditoria for insert to authenticated with check (true);
create policy "metas_auditoria_update_authenticated" on public.metas_auditoria for update to authenticated using (true) with check (true);

grant select, insert, update on public.metas_auditoria to authenticated;
grant usage, select on sequence public.metas_auditoria_id_seq to authenticated;
