create or replace view public.colaboradores_atuais as
select
  id,
  nome,
  regexp_replace(coalesce(cpf, ''), '\D', '', 'g') as cpf,
  tipo,
  cargo,
  supervisao,
  coordenacao,
  empresa,
  situacao,
  (situacao = 'Ativo') as ativo,
  current_date as data_referencia,
  whatsapp,
  email_pessoal,
  email_empresa,
  endereco,
  bairro,
  cidade,
  estado,
  cep,
  admissao,
  desligamento,
  complemento,
  data_nascimento
from public.colaboradores;;
