-- Lote 3 da conciliação de hotéis da planilha "bc hoteis.xlsx".
begin;
select public.hospedagem_conciliar_hotel(
  v.nome,
  v.cidade,
  v.uf,
  v.link_maps,
  v.whatsapp,
  v.endereco,
  v.valor_padrao,
  v.valor_individual,
  v.valor_duplo,
  v.valor_triplo,
  v.valor_quadruplo,
  v.prioridade,
  v.observacoes
)
from (
values
  (E'HOTEL UNIAO', E'CHAPADAO DO SUL', E'MS', E'https://maps.app.goo.gl/V7VdYeMJcK5Cpguv8', E'+556735627308', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL UMUARAMA', E'COLINAS DO TOCANTINS', E'TO', E'https://maps.app.goo.gl/CFHAHoqUnDdFWxSd8', E'+5563984591943', NULL, 56.66, NULL, NULL, 56.66, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL PORTO ALEGRE', E'COMODORO', E'MT', E'https://maps.app.goo.gl/BjSfAeNR3xqZsFRC9', NULL, NULL, 70.00, NULL, 70.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL DIVISA', E'CORRENTINA', E'BA', E'https://maps.app.goo.gl/oYR2TZ2T8HbyPpAS6', NULL, NULL, 110.00, 110.00, 100.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'EX HOTELS BAUS', E'COSTA RICA', E'MS', E'https://maps.app.goo.gl/W6CApNrHbZ1GQHv68', NULL, NULL, 149.00, 149.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'NAÇÕES POUSADA', E'CRICIUMA', E'SC', E'https://maps.app.goo.gl/2bnjrQCcDcsLv5ke6', NULL, NULL, 89.00, 89.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL CENTRAL', E'CRISTALINA', E'GO', E'https://maps.app.goo.gl/e8aDCzX7KxKcfwKG7', E'+556186047575', NULL, 100.00, 100.00, 70.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'POUSADA ERICO VERISSIMO', E'CRUZ ALTA', E'RS', E'https://maps.app.goo.gl/X8PkQoZULsYSWdbn6', NULL, NULL, 145.00, 145.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL CALIFORNIA', E'CRUZ ALTA', E'RS', E'https://maps.app.goo.gl/z32gC9Jyor9Um5kH8', E'+5555991800726', NULL, 105.00, NULL, 105.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'PLEIONE RESIDENCE FLATS', E'CURITIBA', E'PR', E'https://maps.app.goo.gl/FUZRXeEdah7cquAD8', NULL, NULL, 125.00, 125.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL CONFIANCE', E'CURITIBA', E'PR', E'https://maps.app.goo.gl/Kygut1Nn5ejFf2ps7', NULL, NULL, 450.25, 450.25, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'POUSADA DO SOL PARK HOTEL', E'DECIOLANDIA, DIAMANTINO', E'MT', E'https://maps.app.goo.gl/QqubDUaLJKSDJcE77', NULL, NULL, 170.00, 170.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL DESCANSO', E'DESCANSO', E'SC', E'https://maps.app.goo.gl/hqN79WZupSx7xWcC6', E'+5549991010733', NULL, 110.00, NULL, 110.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL E RESTAURANTE VILLA DOS PARECIS', E'DIAMANTINO', E'MT', E'https://maps.app.goo.gl/zSKHwvMSLLQdLvKb9', NULL, NULL, 198.00, 198.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL ARAGUAIA', E'DOIS IRMAOS', E'TO', E'https://maps.app.goo.gl/MGpmLdy6SUNWcEMN8', NULL, NULL, 95.00, 95.00, 65.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL NEVES III', E'DOURADOS', E'MS', E'https://maps.app.goo.gl/MMKomP7jRFhAzuUd7', E'+556734241112', NULL, 107.50, NULL, 107.50, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'FIT HOTEL', E'DOURADOS', E'MS', E'https://maps.app.goo.gl/ekKMaotL6omxqe5V6', E'+5567999073399', NULL, 139.00, 139.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL E POSTO DOVERLANDIA', E'DOVERLANDIA', E'GO', E'https://maps.app.goo.gl/Db2rMNbXuT6qWGck9', E'+556484175363', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL MUNDIAL', E'EDEALINA', E'GO', NULL, E'+5564984120302', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'ERECHIM HOTEL', E'ERECHIM', E'RS', E'https://maps.app.goo.gl/ZnSGhBcpgPPLngFt7', E'+5554999810039', NULL, 136.00, 136.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL BORTOLUZZI', E'FELIZ NATAL', E'MT', E'https://maps.app.goo.gl/XKCb1Ga831DMYRFJ6', E'+5566996396411', NULL, 184.00, 184.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'POUSADA TRAUDI', E'FORMOSA DO RIO PRETO', E'BA', E'https://maps.app.goo.gl/PX8SVrxgu7LaDEMQ8', NULL, E'(VILA PANAMBI)', 130.00, 130.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'POUSADA NOVA VIDA', E'FORMOSA', E'GO', E'https://maps.app.goo.gl/LPUjKKeSK6TdHV7g9', E'+556196727335', NULL, 70.00, NULL, 70.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL POTIGUAR', E'FORMOSA', E'GO', E'https://maps.app.goo.gl/4q8QhJRdhUvCaj2aA', E'+5561996225066', NULL, 90.00, 90.00, 80.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL PLANALTO', E'FORMOSA', E'GO', NULL, E'+5561999367870', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'PETRI PLAZA HOTEL', E'FRANCISCO BELTRÃO', E'PR', E'https://maps.app.goo.gl/yixQ2fQcym2X53VZ7', NULL, NULL, 113.33, NULL, NULL, 113.33, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL VENEZA', E'GAUCHA DO NORTE', E'MT', E'https://maps.app.goo.gl/HU2B7v1hhsWdjvY8A', E'+5566992499890', NULL, 76.66, 76.66, NULL, 80.00, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL AMAZONAS', E'GOIATUBA', E'GO', E'https://maps.app.goo.gl/ZG7rYUccm9tqNxXu9', E'+556493027584', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL MEDRAD''S', E'GOIOERÊ', E'PR', E'https://maps.app.goo.gl/Yh6CbG3QYvuBJXQx9', E'+5544999527277', NULL, 80.00, 80.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL SÃO PAULO', E'IBIÁ', E'MG', E'https://maps.app.goo.gl/yxSqa7ixfxH4Dph68', E'+553436311597', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL VALE DO RIO', E'INACIOLANDIA', E'GO', E'https://maps.app.goo.gl/qrmtRWrCqM3VSxyS7', E'+556434351614', NULL, 87.50, NULL, 87.50, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL DOS VIAJANTES', E'INHUMAS', E'GO', E'https://maps.app.goo.gl/fx1Nqd29UJ2FfEE27', E'+556299430015', NULL, 100.00, 100.00, 90.00, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL LORD', E'IPORA', E'GO', NULL, E'+5562993192460', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'DORMITORIO IPUAÇU', E'IPUAÇU', E'SC', E'https://maps.app.goo.gl/sdCBLUZiVoAenKnb7', E'+5549998092699', NULL, 60.00, 60.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'POUSADA MANANCIAL', E'ITABERAÍ', E'GO', E'https://maps.app.goo.gl/SBTg7hwGppDiAFy46', E'+5562994226629', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'MARRIÊ PALACE HOTEL', E'ITABERAÍ', E'GO', NULL, E'+556291309928', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'ITABERAÍ HOTEL', E'ITABERAÍ', E'GO', NULL, E'+556233752082', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL TROPICAL', E'ITABERAÍ', E'GO', E'https://maps.app.goo.gl/RT8LQKSpHaVcwB71A', E'+5562998115640', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'ELL PALACE HOTEL', E'ITABERAÍ', E'GO', NULL, E'+556233751105', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'MASTER HOTEL 2', E'ITUMBIARA', E'GO', E'https://maps.app.goo.gl/wrLbSL1GMcfTbRrSA', E'+556493018998', NULL, 95.00, 95.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL BAHIA', E'ITUMBIARA', E'GO', E'https://maps.app.goo.gl/go8kvXghbUNK6FSF8', E'+5564992021776', NULL, 120.00, 120.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL PARANOA', E'JABOTICABAL', E'SP', E'https://maps.app.goo.gl/BFD985BsytqGr39a7', E'+5516981983737', NULL, 196.00, 196.00, 144.50, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL CONVENIENTE', E'JABOTICABAL', E'SP', E'https://maps.app.goo.gl/7sgnGcMFHACGk4B1A', E'+5516997586455', NULL, 87.00, 87.00, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'HOTEL SHALOM', E'JOVIANIA', E'GO', E'https://maps.app.goo.gl/iBXM6ymePUmFXQM99', E'+5564993379212', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'BRUGALA HOTEL', E'JOVIANIA', E'GO', NULL, E'+5564999836801', NULL, NULL, NULL, NULL, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx'),
  (E'JANUARIUS HOTEL', E'LAGAMAR', E'MG', E'https://maps.app.goo.gl/huvYguYrsJm935oz6', NULL, NULL, 77.50, NULL, 77.50, NULL, NULL, E'NORMAL', E'Fonte: bc hoteis.xlsx')
) as v(
  nome,
  cidade,
  uf,
  link_maps,
  whatsapp,
  endereco,
  valor_padrao,
  valor_individual,
  valor_duplo,
  valor_triplo,
  valor_quadruplo,
  prioridade,
  observacoes
);
commit;
